goWeb:
  dataSource:
    url: py:123@tcp(localhost:3306)/gorm?charset=utf8&TimeParsed=true&loc=Local
    host: localhost:3306
  mysql:
    url: https://www.mysql.com
  nacos:
    localhost:
      url:127.0.0.1